import { Link, useLocation, useNavigate } from 'react-router-dom'
import { Button } from '@/components/common/Button'
import { EmptyState } from '@/components/common/EmptyState'
import { SectionHeader } from '@/components/common/SectionHeader'
import { PageShell } from '@/components/layout/PageShell'
import { PitchResultDashboard } from '@/components/pitch/PitchResultDashboard'
import { ExportActions } from '@/components/pitch/ExportActions'
import { loadStoredResult } from '@/hooks/usePitchGeneration'
import type { PitchGenerationResult } from '@/types/pitch'

export function PitchResultPage() {
  const location = useLocation()
  const navigate = useNavigate()
  const stateResult = (location.state as { result?: PitchGenerationResult } | null)?.result
  const result = stateResult ?? loadStoredResult()

  if (!result) {
    return (
      <PageShell>
        <div className="mx-auto max-w-lg px-4 py-24 sm:px-6">
          <EmptyState />
        </div>
      </PageShell>
    )
  }

  return (
    <PageShell>
      <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
        <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <SectionHeader
            title="Pitch Package"
            description="Generated by LaunchPad AI — AI-generated starting points for founders."
          />
          <div className="flex flex-wrap gap-2">
            <Button variant="secondary" onClick={() => navigate('/pitch')}>
              Start new idea
            </Button>
            <Link to="/">
              <Button variant="ghost">Home</Button>
            </Link>
          </div>
        </div>
        <ExportActions result={result} />
        <PitchResultDashboard result={result} />
      </div>
    </PageShell>
  )
}
